services:
  nami:
    image: ubuntu
    networks:
      east-blue:
        ipv4_address: 192.168.3.66
    depends_on:
      - usopp
    command: sh -c 'apt update && apt install iputils-ping -y && ping -c 4 usopp && tail -F anything'

  sanji:
    image: node
    networks:
      north-blue:
        ipv4_address: 192.168.1.33
    command: tail -F anything

  chopper:
    image: golang
    networks:
      grand-line:
        ipv4_address: 172.16.0.100
    command: tail -F anything

  usopp:
    image: debian
    networks:
      east-blue:
        ipv4_address: 192.168.3.200
    command: tail -F anything

  robin:
    image: alpine/curl
    entrypoint: ""
    networks:
      west-blue:
        ipv4_address: 192.168.4.130
    depends_on:
      - brook
    command: sh -c 'curl 192.168.4.254 80 && echo "Brook is here!" || echo "Where is Brook?"; tail -F anything'
    
  brook:
    image: nginx
    networks:
      west-blue:
        ipv4_address: 192.168.4.83
    ports:
      - "8080:80"

  franky:
    image: redis
    networks:
      south-blue:
        ipv4_address: 192.168.2.94

networks:
  grand-line:
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.254
  red-line:
    ipam:
      config:
        - subnet: 172.16.1.0/16
          gateway: 172.16.1.254
  north-blue:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
  south-blue:
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254
  east-blue:
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.254
  west-blue:
    ipam:
      config:
        - subnet: 192.168.4.0/24
          gateway: 192.168.4.254